In [1]:
import torch

#f(x) = sin(x1) cos(x2) + sin(0.5x1) cos(0.5x2)

def fx(x):
    x1= x[:, 0]
    x2 = x[:, 1]
    #sin(x1) cos(x2)
    out1 = torch.sin(x1)
    out1 *= torch.cos(x2)

    #sin(0.5x1) cos(0.5x2)
    out2 = torch.sin(0.5 * x1)
    out2 *= torch.cos(0.5 * x2)
    return out1 + out2

def gradient_fx(x):
    x1, x2 = x[:, 0], x[:, 1]
    dfx_dx1 = (torch.cos(x1) * torch.cos(x2)) + (0.5 * torch.cos(0.5*x1) * torch.cos(0.5*x2))
    dfx_dx2 = (-torch.sin(x1) * torch.sin(x2)) - (0.5 * torch.sin(0.5*x1) * torch.sin(0.5*x2))
    return torch.stack((dfx_dx1, dfx_dx2), dim=1)

a = torch.randn(4,2, requires_grad=True)
print(a)

out = fx(a).sum()
print(out)
out.backward()

print(a.grad)

print(gradient_fx(a))



tensor([[-0.1025, -0.2239],
        [ 1.8774,  0.4579],
        [ 1.7245,  1.0279],
        [ 1.1245, -0.4978]], requires_grad=True)
tensor(3.9713, grad_fn=<SumBackward0>)
tensor([[ 1.4661, -0.0256],
        [ 0.0169, -0.5130],
        [ 0.2042, -1.0328],
        [ 0.7892,  0.4964]])
tensor([[ 1.4661, -0.0256],
        [ 0.0169, -0.5130],
        [ 0.2042, -1.0328],
        [ 0.7892,  0.4964]], grad_fn=<StackBackward0>)
